#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: c1050fe
#
# Source0 file verified with key 0x6AACDD263C2CEFD4 (kossebau@kde.org)
#
Name     : okteta
Version  : 0.26.13
Release  : 11
URL      : https://download.kde.org/stable/okteta/0.26.13/src/okteta-0.26.13.tar.xz
Source0  : https://download.kde.org/stable/okteta/0.26.13/src/okteta-0.26.13.tar.xz
Source1  : https://download.kde.org/stable/okteta/0.26.13/src/okteta-0.26.13.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0
Requires: okteta-bin = %{version}-%{release}
Requires: okteta-data = %{version}-%{release}
Requires: okteta-lib = %{version}-%{release}
Requires: okteta-license = %{version}-%{release}
Requires: okteta-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : qca-qt5-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory holds all the char codecs. All it exports is the call "createCodec()", the rest in hidden.

%package bin
Summary: bin components for the okteta package.
Group: Binaries
Requires: okteta-data = %{version}-%{release}
Requires: okteta-license = %{version}-%{release}

%description bin
bin components for the okteta package.


%package data
Summary: data components for the okteta package.
Group: Data

%description data
data components for the okteta package.


%package dev
Summary: dev components for the okteta package.
Group: Development
Requires: okteta-lib = %{version}-%{release}
Requires: okteta-bin = %{version}-%{release}
Requires: okteta-data = %{version}-%{release}
Provides: okteta-devel = %{version}-%{release}
Requires: okteta = %{version}-%{release}

%description dev
dev components for the okteta package.


%package doc
Summary: doc components for the okteta package.
Group: Documentation

%description doc
doc components for the okteta package.


%package lib
Summary: lib components for the okteta package.
Group: Libraries
Requires: okteta-data = %{version}-%{release}
Requires: okteta-license = %{version}-%{release}

%description lib
lib components for the okteta package.


%package license
Summary: license components for the okteta package.
Group: Default

%description license
license components for the okteta package.


%package locales
Summary: locales components for the okteta package.
Group: Default

%description locales
locales components for the okteta package.


%prep
%setup -q -n okteta-0.26.13
cd %{_builddir}/okteta-0.26.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702041423
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1702041423
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/okteta
cp %{_builddir}/okteta-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/okteta/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/okteta-%{version}/LICENSES/GFDL-1.2-or-later.txt %{buildroot}/usr/share/package-licenses/okteta/7697008f58568e61e7598e796eafc2a997503fde || :
cp %{_builddir}/okteta-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/okteta/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/okteta-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/okteta/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/okteta-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/okteta/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/okteta-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/okteta/6f1f675aa5f6a2bbaa573b8343044b166be28399 || :
cp %{_builddir}/okteta-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/okteta/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/okteta-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/okteta/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/okteta-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/okteta/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/okteta-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/okteta/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/okteta-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/okteta/e458941548e0864907e654fa2e192844ae90fc32 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
%find_lang libkasten
%find_lang liboktetacore
%find_lang liboktetakasten
%find_lang okteta
%find_lang oktetapart
%find_lang liboktetagui
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/okteta
/usr/bin/okteta
/usr/bin/struct2osd

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.okteta.desktop
/usr/share/config.kcfg/structureviewpreferences.kcfg
/usr/share/icons/hicolor/128x128/apps/okteta.png
/usr/share/icons/hicolor/16x16/apps/okteta.png
/usr/share/icons/hicolor/22x22/apps/okteta.png
/usr/share/icons/hicolor/32x32/apps/okteta.png
/usr/share/icons/hicolor/48x48/apps/okteta.png
/usr/share/icons/hicolor/64x64/apps/okteta.png
/usr/share/knsrcfiles/okteta-structures.knsrc
/usr/share/kservices5/oktetapart.desktop
/usr/share/metainfo/org.kde.okteta.appdata.xml
/usr/share/mime-packages/okteta.xml
/usr/share/okteta/structures/elf/main.osd
/usr/share/okteta/structures/elf/metadata.desktop
/usr/share/okteta/structures/gccxml-to-osd.xsl
/usr/share/okteta/structures/png/main.osd
/usr/share/okteta/structures/png/metadata.desktop
/usr/share/okteta/structures/uuid.js

%files dev
%defattr(-,root,root,-)
/usr/include/KastenControllers/Kasten/ClipboardControllerFactory
/usr/include/KastenControllers/Kasten/CloseControllerFactory
/usr/include/KastenControllers/Kasten/CopyAsControllerFactory
/usr/include/KastenControllers/Kasten/CreatorControllerFactory
/usr/include/KastenControllers/Kasten/DocumentsToolFactory
/usr/include/KastenControllers/Kasten/DocumentsToolViewFactory
/usr/include/KastenControllers/Kasten/ExportControllerFactory
/usr/include/KastenControllers/Kasten/FileSystemBrowserToolFactory
/usr/include/KastenControllers/Kasten/FileSystemBrowserToolViewFactory
/usr/include/KastenControllers/Kasten/FullScreenControllerFactory
/usr/include/KastenControllers/Kasten/InsertControllerFactory
/usr/include/KastenControllers/Kasten/LoaderControllerFactory
/usr/include/KastenControllers/Kasten/ModifiedBarControllerFactory
/usr/include/KastenControllers/Kasten/QuitControllerFactory
/usr/include/KastenControllers/Kasten/ReadOnlyBarControllerFactory
/usr/include/KastenControllers/Kasten/ReadOnlyControllerFactory
/usr/include/KastenControllers/Kasten/SelectControllerFactory
/usr/include/KastenControllers/Kasten/SetRemoteControllerFactory
/usr/include/KastenControllers/Kasten/SwitchViewControllerFactory
/usr/include/KastenControllers/Kasten/SynchronizeControllerFactory
/usr/include/KastenControllers/Kasten/TerminalToolFactory
/usr/include/KastenControllers/Kasten/TerminalToolViewFactory
/usr/include/KastenControllers/Kasten/ToolListMenuControllerFactory
/usr/include/KastenControllers/Kasten/UiColorSchemeControllerFactory
/usr/include/KastenControllers/Kasten/VersionControllerFactory
/usr/include/KastenControllers/Kasten/VersionViewToolFactory
/usr/include/KastenControllers/Kasten/VersionViewToolViewFactory
/usr/include/KastenControllers/Kasten/ViewAreaContextMenuControllerFactory
/usr/include/KastenControllers/Kasten/ViewAreaSplitControllerFactory
/usr/include/KastenControllers/Kasten/ViewListMenuControllerFactory
/usr/include/KastenControllers/Kasten/ZoomBarControllerFactory
/usr/include/KastenControllers/Kasten/ZoomControllerFactory
/usr/include/KastenControllers/kasten/clipboardcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/closecontrollerfactory.hpp
/usr/include/KastenControllers/kasten/copyascontrollerfactory.hpp
/usr/include/KastenControllers/kasten/creatorcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/documentstoolfactory.hpp
/usr/include/KastenControllers/kasten/documentstoolviewfactory.hpp
/usr/include/KastenControllers/kasten/exportcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/filesystembrowsertoolfactory.hpp
/usr/include/KastenControllers/kasten/filesystembrowsertoolviewfactory.hpp
/usr/include/KastenControllers/kasten/fullscreencontrollerfactory.hpp
/usr/include/KastenControllers/kasten/insertcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/kastencontrollers_export.hpp
/usr/include/KastenControllers/kasten/loadercontrollerfactory.hpp
/usr/include/KastenControllers/kasten/modifiedbarcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/quitcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/readonlybarcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/readonlycontrollerfactory.hpp
/usr/include/KastenControllers/kasten/selectcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/setremotecontrollerfactory.hpp
/usr/include/KastenControllers/kasten/switchviewcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/synchronizecontrollerfactory.hpp
/usr/include/KastenControllers/kasten/terminaltoolfactory.hpp
/usr/include/KastenControllers/kasten/terminaltoolviewfactory.hpp
/usr/include/KastenControllers/kasten/toollistmenucontrollerfactory.hpp
/usr/include/KastenControllers/kasten/uicolorschemecontrollerfactory.hpp
/usr/include/KastenControllers/kasten/versioncontrollerfactory.hpp
/usr/include/KastenControllers/kasten/versionviewtoolfactory.hpp
/usr/include/KastenControllers/kasten/versionviewtoolviewfactory.hpp
/usr/include/KastenControllers/kasten/viewareacontextmenucontrollerfactory.hpp
/usr/include/KastenControllers/kasten/viewareasplitcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/viewlistmenucontrollerfactory.hpp
/usr/include/KastenControllers/kasten/zoombarcontrollerfactory.hpp
/usr/include/KastenControllers/kasten/zoomcontrollerfactory.hpp
/usr/include/KastenCore/Kasten/AbstractConnectJob
/usr/include/KastenCore/Kasten/AbstractDocument
/usr/include/KastenCore/Kasten/AbstractDocumentFactory
/usr/include/KastenCore/Kasten/AbstractExportJob
/usr/include/KastenCore/Kasten/AbstractFileSystemConnectJob
/usr/include/KastenCore/Kasten/AbstractFileSystemExportJob
/usr/include/KastenCore/Kasten/AbstractFileSystemLoadJob
/usr/include/KastenCore/Kasten/AbstractFileSystemSyncFromRemoteJob
/usr/include/KastenCore/Kasten/AbstractFileSystemSyncToRemoteJob
/usr/include/KastenCore/Kasten/AbstractFileSystemSyncWithRemoteJob
/usr/include/KastenCore/Kasten/AbstractLoadJob
/usr/include/KastenCore/Kasten/AbstractModel
/usr/include/KastenCore/Kasten/AbstractModelDataGenerator
/usr/include/KastenCore/Kasten/AbstractModelExporter
/usr/include/KastenCore/Kasten/AbstractModelFileSystemSynchronizer
/usr/include/KastenCore/Kasten/AbstractModelSelection
/usr/include/KastenCore/Kasten/AbstractModelStreamEncoder
/usr/include/KastenCore/Kasten/AbstractModelSynchronizer
/usr/include/KastenCore/Kasten/AbstractModelSynchronizerFactory
/usr/include/KastenCore/Kasten/AbstractOverwriteDialog
/usr/include/KastenCore/Kasten/AbstractSaveDiscardDialog
/usr/include/KastenCore/Kasten/AbstractSyncFromRemoteJob
/usr/include/KastenCore/Kasten/AbstractSyncToRemoteJob
/usr/include/KastenCore/Kasten/AbstractSyncWithRemoteJob
/usr/include/KastenCore/Kasten/AbstractTool
/usr/include/KastenCore/Kasten/AbstractToolFactory
/usr/include/KastenCore/Kasten/DocumentCreateManager
/usr/include/KastenCore/Kasten/DocumentManager
/usr/include/KastenCore/Kasten/DocumentSyncManager
/usr/include/KastenCore/Kasten/DocumentVersionData
/usr/include/KastenCore/Kasten/DocumentVersionId
/usr/include/KastenCore/Kasten/JobManager
/usr/include/KastenCore/Kasten/KastenCore
/usr/include/KastenCore/Kasten/ModelCodecManager
/usr/include/KastenCore/Kasten/ModelDataGenerateThread
/usr/include/KastenCore/Kasten/ModelEncoderFileSystemExportJob
/usr/include/KastenCore/Kasten/ModelEncoderFileSystemExporter
/usr/include/KastenCore/Kasten/ModelStreamEncodeThread
/usr/include/KastenCore/Kasten/Versionable
/usr/include/KastenCore/kasten/abstractconnectjob.hpp
/usr/include/KastenCore/kasten/abstractdocument.hpp
/usr/include/KastenCore/kasten/abstractdocumentfactory.hpp
/usr/include/KastenCore/kasten/abstractexportjob.hpp
/usr/include/KastenCore/kasten/abstractfilesystemconnectjob.hpp
/usr/include/KastenCore/kasten/abstractfilesystemexportjob.hpp
/usr/include/KastenCore/kasten/abstractfilesystemloadjob.hpp
/usr/include/KastenCore/kasten/abstractfilesystemsyncfromremotejob.hpp
/usr/include/KastenCore/kasten/abstractfilesystemsynctoremotejob.hpp
/usr/include/KastenCore/kasten/abstractfilesystemsyncwithremotejob.hpp
/usr/include/KastenCore/kasten/abstractloadjob.hpp
/usr/include/KastenCore/kasten/abstractmodel.hpp
/usr/include/KastenCore/kasten/abstractmodeldatagenerator.hpp
/usr/include/KastenCore/kasten/abstractmodelexporter.hpp
/usr/include/KastenCore/kasten/abstractmodelfilesystemsynchronizer.hpp
/usr/include/KastenCore/kasten/abstractmodelselection.hpp
/usr/include/KastenCore/kasten/abstractmodelstreamencoder.hpp
/usr/include/KastenCore/kasten/abstractmodelsynchronizer.hpp
/usr/include/KastenCore/kasten/abstractmodelsynchronizerfactory.hpp
/usr/include/KastenCore/kasten/abstractoverwritedialog.hpp
/usr/include/KastenCore/kasten/abstractsavediscarddialog.hpp
/usr/include/KastenCore/kasten/abstractsyncfromremotejob.hpp
/usr/include/KastenCore/kasten/abstractsynctoremotejob.hpp
/usr/include/KastenCore/kasten/abstractsyncwithremotejob.hpp
/usr/include/KastenCore/kasten/abstracttool.hpp
/usr/include/KastenCore/kasten/abstracttoolfactory.hpp
/usr/include/KastenCore/kasten/documentcreatemanager.hpp
/usr/include/KastenCore/kasten/documentmanager.hpp
/usr/include/KastenCore/kasten/documentsyncmanager.hpp
/usr/include/KastenCore/kasten/documentversiondata.hpp
/usr/include/KastenCore/kasten/documentversionid.hpp
/usr/include/KastenCore/kasten/jobmanager.hpp
/usr/include/KastenCore/kasten/kastencore.hpp
/usr/include/KastenCore/kasten/kastencore_export.hpp
/usr/include/KastenCore/kasten/modelcodecmanager.hpp
/usr/include/KastenCore/kasten/modeldatageneratethread.hpp
/usr/include/KastenCore/kasten/modelencoderfilesystemexporter.hpp
/usr/include/KastenCore/kasten/modelencoderfilesystemexportjob.hpp
/usr/include/KastenCore/kasten/modelstreamencodethread.hpp
/usr/include/KastenCore/kasten/versionable.hpp
/usr/include/KastenGui/Kasten/AbstractDocumentStrategy
/usr/include/KastenGui/Kasten/AbstractGroupedViews
/usr/include/KastenGui/Kasten/AbstractLinePopup
/usr/include/KastenGui/Kasten/AbstractModelDataGeneratorConfigEditor
/usr/include/KastenGui/Kasten/AbstractModelDataGeneratorConfigEditorFactory
/usr/include/KastenGui/Kasten/AbstractModelExporterConfigEditor
/usr/include/KastenGui/Kasten/AbstractModelExporterConfigEditorFactory
/usr/include/KastenGui/Kasten/AbstractModelStreamEncoderConfigEditor
/usr/include/KastenGui/Kasten/AbstractModelStreamEncoderConfigEditorFactory
/usr/include/KastenGui/Kasten/AbstractSelectionView
/usr/include/KastenGui/Kasten/AbstractToolInlineView
/usr/include/KastenGui/Kasten/AbstractToolView
/usr/include/KastenGui/Kasten/AbstractToolViewFactory
/usr/include/KastenGui/Kasten/AbstractToolWidget
/usr/include/KastenGui/Kasten/AbstractView
/usr/include/KastenGui/Kasten/AbstractViewArea
/usr/include/KastenGui/Kasten/AbstractViewFactory
/usr/include/KastenGui/Kasten/AbstractXmlGuiController
/usr/include/KastenGui/Kasten/AbstractXmlGuiControllerFactory
/usr/include/KastenGui/Kasten/DataSelectable
/usr/include/KastenGui/Kasten/DialogHandler
/usr/include/KastenGui/Kasten/DummyView
/usr/include/KastenGui/Kasten/KastenGui
/usr/include/KastenGui/Kasten/ModelCodecViewManager
/usr/include/KastenGui/Kasten/ModelEncoderFileSystemExporterConfigEditor
/usr/include/KastenGui/Kasten/ModelEncoderFileSystemExporterConfigEditorFactory
/usr/include/KastenGui/Kasten/MultiDocumentStrategy
/usr/include/KastenGui/Kasten/MultiViewAreas
/usr/include/KastenGui/Kasten/SelectedDataWriteable
/usr/include/KastenGui/Kasten/ShellWindow
/usr/include/KastenGui/Kasten/SingleDocumentStrategy
/usr/include/KastenGui/Kasten/SingleViewArea
/usr/include/KastenGui/Kasten/SingleViewWindow
/usr/include/KastenGui/Kasten/StatusBar
/usr/include/KastenGui/Kasten/TabbedViews
/usr/include/KastenGui/Kasten/ToggleButton
/usr/include/KastenGui/Kasten/ToolInlineViewable
/usr/include/KastenGui/Kasten/ToolViewDockWidget
/usr/include/KastenGui/Kasten/ViewAreaSplitable
/usr/include/KastenGui/Kasten/ViewManager
/usr/include/KastenGui/Kasten/WidgetsDockable
/usr/include/KastenGui/Kasten/Zoomable
/usr/include/KastenGui/kasten/abstractdocumentstrategy.hpp
/usr/include/KastenGui/kasten/abstractgroupedviews.hpp
/usr/include/KastenGui/kasten/abstractlinepopup.hpp
/usr/include/KastenGui/kasten/abstractmodeldatageneratorconfigeditor.hpp
/usr/include/KastenGui/kasten/abstractmodeldatageneratorconfigeditorfactory.hpp
/usr/include/KastenGui/kasten/abstractmodelexporterconfigeditor.hpp
/usr/include/KastenGui/kasten/abstractmodelexporterconfigeditorfactory.hpp
/usr/include/KastenGui/kasten/abstractmodelstreamencoderconfigeditor.hpp
/usr/include/KastenGui/kasten/abstractmodelstreamencoderconfigeditorfactory.hpp
/usr/include/KastenGui/kasten/abstractselectionview.hpp
/usr/include/KastenGui/kasten/abstracttoolinlineview.hpp
/usr/include/KastenGui/kasten/abstracttoolview.hpp
/usr/include/KastenGui/kasten/abstracttoolviewfactory.hpp
/usr/include/KastenGui/kasten/abstracttoolwidget.hpp
/usr/include/KastenGui/kasten/abstractview.hpp
/usr/include/KastenGui/kasten/abstractviewarea.hpp
/usr/include/KastenGui/kasten/abstractviewfactory.hpp
/usr/include/KastenGui/kasten/abstractxmlguicontroller.hpp
/usr/include/KastenGui/kasten/abstractxmlguicontrollerfactory.hpp
/usr/include/KastenGui/kasten/dataselectable.hpp
/usr/include/KastenGui/kasten/dialoghandler.hpp
/usr/include/KastenGui/kasten/dummyview.hpp
/usr/include/KastenGui/kasten/kastengui.hpp
/usr/include/KastenGui/kasten/kastengui_export.hpp
/usr/include/KastenGui/kasten/modelcodecviewmanager.hpp
/usr/include/KastenGui/kasten/modelencoderfilesystemexporterconfigeditor.hpp
/usr/include/KastenGui/kasten/modelencoderfilesystemexporterconfigeditorfactory.hpp
/usr/include/KastenGui/kasten/multidocumentstrategy.hpp
/usr/include/KastenGui/kasten/multiviewareas.hpp
/usr/include/KastenGui/kasten/selecteddatawriteable.hpp
/usr/include/KastenGui/kasten/shellwindow.hpp
/usr/include/KastenGui/kasten/singledocumentstrategy.hpp
/usr/include/KastenGui/kasten/singleviewarea.hpp
/usr/include/KastenGui/kasten/singleviewwindow.hpp
/usr/include/KastenGui/kasten/statusbar.hpp
/usr/include/KastenGui/kasten/tabbedviews.hpp
/usr/include/KastenGui/kasten/togglebutton.hpp
/usr/include/KastenGui/kasten/toolinlineviewable.hpp
/usr/include/KastenGui/kasten/toolviewdockwidget.hpp
/usr/include/KastenGui/kasten/viewareasplitable.hpp
/usr/include/KastenGui/kasten/viewmanager.hpp
/usr/include/KastenGui/kasten/widgetsdockable.hpp
/usr/include/KastenGui/kasten/zoomable.hpp
/usr/include/OktetaCore/Okteta/AbstractByteArrayModel
/usr/include/OktetaCore/Okteta/Address
/usr/include/OktetaCore/Okteta/AddressRange
/usr/include/OktetaCore/Okteta/ArrayChangeMetrics
/usr/include/OktetaCore/Okteta/ArrayChangeMetricsList
/usr/include/OktetaCore/Okteta/Bookmark
/usr/include/OktetaCore/Okteta/Bookmarkable
/usr/include/OktetaCore/Okteta/BookmarksConstIterator
/usr/include/OktetaCore/Okteta/BookmarksConstIteratorAdapter
/usr/include/OktetaCore/Okteta/Byte
/usr/include/OktetaCore/Okteta/ByteArrayChange
/usr/include/OktetaCore/Okteta/ByteArrayModel
/usr/include/OktetaCore/Okteta/ChangeHistory
/usr/include/OktetaCore/Okteta/ChangesDescribable
/usr/include/OktetaCore/Okteta/CharCodec
/usr/include/OktetaCore/Okteta/Character
/usr/include/OktetaCore/Okteta/NumberRange
/usr/include/OktetaCore/Okteta/OktetaCore
/usr/include/OktetaCore/Okteta/PieceTableByteArrayModel
/usr/include/OktetaCore/Okteta/Range
/usr/include/OktetaCore/Okteta/Size
/usr/include/OktetaCore/Okteta/TextByteArrayAnalyzer
/usr/include/OktetaCore/Okteta/ValueCodec
/usr/include/OktetaCore/Okteta/Versionable
/usr/include/OktetaCore/okteta/abstractbytearraymodel.hpp
/usr/include/OktetaCore/okteta/address.hpp
/usr/include/OktetaCore/okteta/addressrange.hpp
/usr/include/OktetaCore/okteta/arraychangemetrics.hpp
/usr/include/OktetaCore/okteta/arraychangemetricslist.hpp
/usr/include/OktetaCore/okteta/bookmark.hpp
/usr/include/OktetaCore/okteta/bookmarkable.hpp
/usr/include/OktetaCore/okteta/bookmarksconstiterator.hpp
/usr/include/OktetaCore/okteta/bookmarksconstiteratoradapter.hpp
/usr/include/OktetaCore/okteta/byte.hpp
/usr/include/OktetaCore/okteta/bytearraychange.hpp
/usr/include/OktetaCore/okteta/bytearraymodel.hpp
/usr/include/OktetaCore/okteta/changehistory.hpp
/usr/include/OktetaCore/okteta/changesdescribable.hpp
/usr/include/OktetaCore/okteta/character.hpp
/usr/include/OktetaCore/okteta/charcodec.hpp
/usr/include/OktetaCore/okteta/numberrange.hpp
/usr/include/OktetaCore/okteta/oktetacore.hpp
/usr/include/OktetaCore/okteta/oktetacore_export.hpp
/usr/include/OktetaCore/okteta/piecetablebytearraymodel.hpp
/usr/include/OktetaCore/okteta/range.hpp
/usr/include/OktetaCore/okteta/size.hpp
/usr/include/OktetaCore/okteta/textbytearrayanalyzer.hpp
/usr/include/OktetaCore/okteta/valuecodec.hpp
/usr/include/OktetaCore/okteta/versionable.hpp
/usr/include/OktetaGui/Okteta/AbstractByteArrayColumnRenderer
/usr/include/OktetaGui/Okteta/AbstractByteArrayView
/usr/include/OktetaGui/Okteta/AbstractColumnRenderer
/usr/include/OktetaGui/Okteta/AbstractColumnStylist
/usr/include/OktetaGui/Okteta/BorderColumnRenderer
/usr/include/OktetaGui/Okteta/ByteArrayColumnView
/usr/include/OktetaGui/Okteta/ByteArrayRowColumnRenderer
/usr/include/OktetaGui/Okteta/ByteArrayRowView
/usr/include/OktetaGui/Okteta/ByteArrayTableLayout
/usr/include/OktetaGui/Okteta/ByteArrayTableRanges
/usr/include/OktetaGui/Okteta/CharByteArrayColumnRenderer
/usr/include/OktetaGui/Okteta/ColumnsView
/usr/include/OktetaGui/Okteta/Coord
/usr/include/OktetaGui/Okteta/CoordRange
/usr/include/OktetaGui/Okteta/CoordRangeList
/usr/include/OktetaGui/Okteta/Line
/usr/include/OktetaGui/Okteta/LinePosition
/usr/include/OktetaGui/Okteta/LinePositionRange
/usr/include/OktetaGui/Okteta/LineRange
/usr/include/OktetaGui/Okteta/OffsetColumnRenderer
/usr/include/OktetaGui/Okteta/OffsetFormat
/usr/include/OktetaGui/Okteta/OktetaGui
/usr/include/OktetaGui/Okteta/PixelMetrics
/usr/include/OktetaGui/Okteta/Selection
/usr/include/OktetaGui/Okteta/ValueByteArrayColumnRenderer
/usr/include/OktetaGui/Okteta/WidgetColumnStylist
/usr/include/OktetaGui/okteta/abstractbytearraycolumnrenderer.hpp
/usr/include/OktetaGui/okteta/abstractbytearrayview.hpp
/usr/include/OktetaGui/okteta/abstractcolumnrenderer.hpp
/usr/include/OktetaGui/okteta/abstractcolumnstylist.hpp
/usr/include/OktetaGui/okteta/bordercolumnrenderer.hpp
/usr/include/OktetaGui/okteta/bytearraycolumnview.hpp
/usr/include/OktetaGui/okteta/bytearrayrowcolumnrenderer.hpp
/usr/include/OktetaGui/okteta/bytearrayrowview.hpp
/usr/include/OktetaGui/okteta/bytearraytablelayout.hpp
/usr/include/OktetaGui/okteta/bytearraytableranges.hpp
/usr/include/OktetaGui/okteta/charbytearraycolumnrenderer.hpp
/usr/include/OktetaGui/okteta/columnsview.hpp
/usr/include/OktetaGui/okteta/coord.hpp
/usr/include/OktetaGui/okteta/coordrange.hpp
/usr/include/OktetaGui/okteta/coordrangelist.hpp
/usr/include/OktetaGui/okteta/line.hpp
/usr/include/OktetaGui/okteta/lineposition.hpp
/usr/include/OktetaGui/okteta/linepositionrange.hpp
/usr/include/OktetaGui/okteta/linerange.hpp
/usr/include/OktetaGui/okteta/offsetcolumnrenderer.hpp
/usr/include/OktetaGui/okteta/offsetformat.hpp
/usr/include/OktetaGui/okteta/oktetagui.hpp
/usr/include/OktetaGui/okteta/oktetagui_export.hpp
/usr/include/OktetaGui/okteta/pixelmetrics.hpp
/usr/include/OktetaGui/okteta/selection.hpp
/usr/include/OktetaGui/okteta/valuebytearraycolumnrenderer.hpp
/usr/include/OktetaGui/okteta/widgetcolumnstylist.hpp
/usr/include/OktetaKastenControllers/Kasten/Okteta/BookmarksControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/BookmarksToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/BookmarksToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ByteTableToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ByteTableToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/CharsetConversionToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/CharsetConversionToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ChecksumToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ChecksumToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/DocumentInfoToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/DocumentInfoToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/FilterToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/FilterToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/FindDirection
/usr/include/OktetaKastenControllers/Kasten/Okteta/GotoOffsetControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/InfoToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/InfoToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/OverwriteModeControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/PODDecoderToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/PODDecoderToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/PrintControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ReplaceControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/SearchControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/SelectRangeControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/StringsExtractToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/StringsExtractToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/StructuresToolFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/StructuresToolViewFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ViewConfigControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ViewContextMenuControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ViewModeControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ViewProfileControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ViewProfilesManageControllerFactory
/usr/include/OktetaKastenControllers/Kasten/Okteta/ViewStatusControllerFactory
/usr/include/OktetaKastenControllers/kasten/okteta/bookmarkscontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/bookmarkstoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/bookmarkstoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/bytetabletoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/bytetabletoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/charsetconversiontoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/charsetconversiontoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/checksumtoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/checksumtoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/config-qca2.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/documentinfotoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/documentinfotoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/filtertoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/filtertoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/finddirection.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/gotooffsetcontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/infotoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/infotoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/oktetakastencontrollers_export.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/overwritemodecontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/poddecodertoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/poddecodertoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/printcontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/replacecontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/searchcontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/selectrangecontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/stringsextracttoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/stringsextracttoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/structurestoolfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/structurestoolviewfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/viewconfigcontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/viewcontextmenucontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/viewmodecontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/viewprofilecontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/viewprofilesmanagecontrollerfactory.hpp
/usr/include/OktetaKastenControllers/kasten/okteta/viewstatuscontrollerfactory.hpp
/usr/include/OktetaKastenCore/Kasten/Okteta/ByteArrayDocument
/usr/include/OktetaKastenCore/Kasten/Okteta/ByteArrayDocumentFactory
/usr/include/OktetaKastenCore/Kasten/Okteta/ByteArrayRawFileSynchronizer
/usr/include/OktetaKastenCore/Kasten/Okteta/ByteArrayRawFileSynchronizerFactory
/usr/include/OktetaKastenCore/Kasten/Okteta/ByteArraySelection
/usr/include/OktetaKastenCore/kasten/okteta/bytearraydocument.hpp
/usr/include/OktetaKastenCore/kasten/okteta/bytearraydocumentfactory.hpp
/usr/include/OktetaKastenCore/kasten/okteta/bytearrayrawfilesynchronizer.hpp
/usr/include/OktetaKastenCore/kasten/okteta/bytearrayrawfilesynchronizerfactory.hpp
/usr/include/OktetaKastenCore/kasten/okteta/bytearrayselection.hpp
/usr/include/OktetaKastenCore/kasten/okteta/oktetakastencore_export.hpp
/usr/include/OktetaKastenGui/Kasten/Okteta/AbstractByteArrayStreamEncoder
/usr/include/OktetaKastenGui/Kasten/Okteta/AddressComboBox
/usr/include/OktetaKastenGui/Kasten/Okteta/AddressValidator
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayComboBox
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayDataGeneratorConfigEditorFactoryFactory
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayDataGeneratorFactory
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayStreamEncoderConfigEditorFactoryFactory
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayStreamEncoderFactory
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayView
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayViewFactory
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayViewProfile
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayViewProfileLock
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayViewProfileManager
/usr/include/OktetaKastenGui/Kasten/Okteta/ByteArrayViewProfileSynchronizer
/usr/include/OktetaKastenGui/Kasten/Okteta/OktetaKastenGui
/usr/include/OktetaKastenGui/kasten/okteta/abstractbytearraystreamencoder.hpp
/usr/include/OktetaKastenGui/kasten/okteta/addresscombobox.hpp
/usr/include/OktetaKastenGui/kasten/okteta/addressvalidator.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearraycombobox.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearraydatageneratorconfigeditorfactoryfactory.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearraydatageneratorfactory.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearraystreamencoderconfigeditorfactoryfactory.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearraystreamencoderfactory.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearrayview.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearrayviewfactory.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearrayviewprofile.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearrayviewprofilelock.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearrayviewprofilemanager.hpp
/usr/include/OktetaKastenGui/kasten/okteta/bytearrayviewprofilesynchronizer.hpp
/usr/include/OktetaKastenGui/kasten/okteta/oktetakastengui.hpp
/usr/include/OktetaKastenGui/kasten/okteta/oktetakastengui_export.hpp
/usr/lib64/cmake/KastenControllers/KastenControllersConfig.cmake
/usr/lib64/cmake/KastenControllers/KastenControllersConfigVersion.cmake
/usr/lib64/cmake/KastenControllers/KastenControllersTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KastenControllers/KastenControllersTargets.cmake
/usr/lib64/cmake/KastenCore/KastenCoreConfig.cmake
/usr/lib64/cmake/KastenCore/KastenCoreConfigVersion.cmake
/usr/lib64/cmake/KastenCore/KastenCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KastenCore/KastenCoreTargets.cmake
/usr/lib64/cmake/KastenGui/KastenGuiConfig.cmake
/usr/lib64/cmake/KastenGui/KastenGuiConfigVersion.cmake
/usr/lib64/cmake/KastenGui/KastenGuiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KastenGui/KastenGuiTargets.cmake
/usr/lib64/cmake/OktetaCore/OktetaCoreConfig.cmake
/usr/lib64/cmake/OktetaCore/OktetaCoreConfigVersion.cmake
/usr/lib64/cmake/OktetaCore/OktetaCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OktetaCore/OktetaCoreTargets.cmake
/usr/lib64/cmake/OktetaGui/OktetaGuiConfig.cmake
/usr/lib64/cmake/OktetaGui/OktetaGuiConfigVersion.cmake
/usr/lib64/cmake/OktetaGui/OktetaGuiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OktetaGui/OktetaGuiTargets.cmake
/usr/lib64/cmake/OktetaKastenControllers/OktetaKastenControllersConfig.cmake
/usr/lib64/cmake/OktetaKastenControllers/OktetaKastenControllersConfigVersion.cmake
/usr/lib64/cmake/OktetaKastenControllers/OktetaKastenControllersTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OktetaKastenControllers/OktetaKastenControllersTargets.cmake
/usr/lib64/cmake/OktetaKastenCore/OktetaKastenCoreConfig.cmake
/usr/lib64/cmake/OktetaKastenCore/OktetaKastenCoreConfigVersion.cmake
/usr/lib64/cmake/OktetaKastenCore/OktetaKastenCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OktetaKastenCore/OktetaKastenCoreTargets.cmake
/usr/lib64/cmake/OktetaKastenGui/OktetaKastenGuiConfig.cmake
/usr/lib64/cmake/OktetaKastenGui/OktetaKastenGuiConfigVersion.cmake
/usr/lib64/cmake/OktetaKastenGui/OktetaKastenGuiTargets-relwithdebinfo.cmake
/usr/lib64/cmake/OktetaKastenGui/OktetaKastenGuiTargets.cmake
/usr/lib64/libKasten4Controllers.so
/usr/lib64/libKasten4Core.so
/usr/lib64/libKasten4Gui.so
/usr/lib64/libKasten4Okteta2Controllers.so
/usr/lib64/libKasten4Okteta2Core.so
/usr/lib64/libKasten4Okteta2Gui.so
/usr/lib64/libOkteta3Core.so
/usr/lib64/libOkteta3Gui.so
/usr/lib64/pkgconfig/OktetaCore.pc
/usr/lib64/pkgconfig/OktetaGui.pc
/usr/lib64/qt5/mkspecs/modules/qt_OktetaCore.pri
/usr/lib64/qt5/mkspecs/modules/qt_OktetaGui.pri

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/okteta/index.cache.bz2
/usr/share/doc/HTML/ca/okteta/index.docbook
/usr/share/doc/HTML/de/okteta/index.cache.bz2
/usr/share/doc/HTML/de/okteta/index.docbook
/usr/share/doc/HTML/en/okteta/index.cache.bz2
/usr/share/doc/HTML/en/okteta/index.docbook
/usr/share/doc/HTML/es/okteta/index.cache.bz2
/usr/share/doc/HTML/es/okteta/index.docbook
/usr/share/doc/HTML/it/okteta/index.cache.bz2
/usr/share/doc/HTML/it/okteta/index.docbook
/usr/share/doc/HTML/nl/okteta/index.cache.bz2
/usr/share/doc/HTML/nl/okteta/index.docbook
/usr/share/doc/HTML/pt/okteta/index.cache.bz2
/usr/share/doc/HTML/pt/okteta/index.docbook
/usr/share/doc/HTML/pt_BR/okteta/index.cache.bz2
/usr/share/doc/HTML/pt_BR/okteta/index.docbook
/usr/share/doc/HTML/sr/okteta/index.cache.bz2
/usr/share/doc/HTML/sr/okteta/index.docbook
/usr/share/doc/HTML/sr@latin/okteta/index.cache.bz2
/usr/share/doc/HTML/sr@latin/okteta/index.docbook
/usr/share/doc/HTML/sv/okteta/index.cache.bz2
/usr/share/doc/HTML/sv/okteta/index.docbook
/usr/share/doc/HTML/uk/okteta/index.cache.bz2
/usr/share/doc/HTML/uk/okteta/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKasten4Controllers.so.0.4.1
/V3/usr/lib64/libKasten4Core.so.0.4.1
/V3/usr/lib64/libKasten4Gui.so.0.4.1
/V3/usr/lib64/libKasten4Okteta2Controllers.so.0.4.0
/V3/usr/lib64/libKasten4Okteta2Core.so.0.4.0
/V3/usr/lib64/libKasten4Okteta2Gui.so.0.4.0
/V3/usr/lib64/libOkteta3Core.so.0.10.0
/V3/usr/lib64/libOkteta3Gui.so.0.10.0
/V3/usr/lib64/qt5/plugins/designer/oktetawidgets.so
/V3/usr/lib64/qt5/plugins/kf5/parts/oktetapart.so
/usr/lib64/libKasten4Controllers.so.0
/usr/lib64/libKasten4Controllers.so.0.4.1
/usr/lib64/libKasten4Core.so.0
/usr/lib64/libKasten4Core.so.0.4.1
/usr/lib64/libKasten4Gui.so.0
/usr/lib64/libKasten4Gui.so.0.4.1
/usr/lib64/libKasten4Okteta2Controllers.so.0
/usr/lib64/libKasten4Okteta2Controllers.so.0.4.0
/usr/lib64/libKasten4Okteta2Core.so.0
/usr/lib64/libKasten4Okteta2Core.so.0.4.0
/usr/lib64/libKasten4Okteta2Gui.so.0
/usr/lib64/libKasten4Okteta2Gui.so.0.4.0
/usr/lib64/libOkteta3Core.so.0
/usr/lib64/libOkteta3Core.so.0.10.0
/usr/lib64/libOkteta3Gui.so.0
/usr/lib64/libOkteta3Gui.so.0.10.0
/usr/lib64/qt5/plugins/designer/oktetawidgets.so
/usr/lib64/qt5/plugins/kf5/parts/oktetapart.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/okteta/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/okteta/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/okteta/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/okteta/6f1f675aa5f6a2bbaa573b8343044b166be28399
/usr/share/package-licenses/okteta/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/okteta/7697008f58568e61e7598e796eafc2a997503fde
/usr/share/package-licenses/okteta/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/okteta/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/okteta/e458941548e0864907e654fa2e192844ae90fc32

%files locales -f libkasten.lang -f liboktetacore.lang -f liboktetakasten.lang -f okteta.lang -f oktetapart.lang -f liboktetagui.lang
%defattr(-,root,root,-)

